// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArBAbqAyDj7VodBfOKjS1VV09y9hq8QL8',
    appId: '1:219232402763:web:c1bf42139152725819fcce',
    messagingSenderId: '219232402763',
    projectId: 'book-store-99a01',
    authDomain: 'book-store-99a01.firebaseapp.com',
    storageBucket: 'book-store-99a01.appspot.com',
    measurementId: 'G-PC838RKSNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_o8WY0B5p_qmxZbEMIvVTA92YY6dNetM',
    appId: '1:219232402763:android:4a3c274c3651d5ee19fcce',
    messagingSenderId: '219232402763',
    projectId: 'book-store-99a01',
    storageBucket: 'book-store-99a01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPyVQl-tL1YAbldTU9TP90BQxeUiwj6YQ',
    appId: '1:219232402763:ios:8417867fc20a6d0319fcce',
    messagingSenderId: '219232402763',
    projectId: 'book-store-99a01',
    storageBucket: 'book-store-99a01.appspot.com',
    iosClientId: '219232402763-fuhec8m04d1o0m85cpn3mevoquoh2etk.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPyVQl-tL1YAbldTU9TP90BQxeUiwj6YQ',
    appId: '1:219232402763:ios:8417867fc20a6d0319fcce',
    messagingSenderId: '219232402763',
    projectId: 'book-store-99a01',
    storageBucket: 'book-store-99a01.appspot.com',
    iosClientId: '219232402763-fuhec8m04d1o0m85cpn3mevoquoh2etk.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp',
  );
}
